worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

# remote_learning_backend_db_1 is the service name + _ + filename of the V1.001__users.sql
dbconnection: 'postgresql://testsuite@localhost:15433/remote_learning_backend_db_1'
