components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stdout'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        auth-database:
            dbconnection: '$dbconnection'
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        #auth-pg-cache:
        #    pgcomponent: auth-database
        #    update-interval: 10s

        default-server-middleware-pipeline-builder:
            append:
                - cors-middleware

        handler-login:
            path: /v1/login
            task_processor: main-task-processor
            method: POST,OPTIONS
            #middlewares:
            #    pipeline-builder: cors-pipeline-builder
#            auth: # Authorization config for this handler
#                types:
#                    - bearer  # Authorization type that was specified in main()
#                scopes: # Required user scopes for that handler
#                    - read
#                    - hello
        handler-register:
            path: /v1/register
            task_processor: main-task-processor
            method: POST,OPTIONS
            #middlewares:
            #    pipeline-builder: cors-pipeline-builder

        handler-department-add:
            path: /v1/admin/department/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-department-group-add:
            path: /v1/admin/department/group/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-faculty-add:
            path: /v1/admin/faculty/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-student-add:
            path: /v1/admin/student/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-teacher-student-to-existing-subject-group-add:
            path: /v1/admin/department/group/add_student
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-subject-add:
            path: /v1/admin/department/subject/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-subject-group-add:
            path: /v1/admin/subject/group/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-subject-group-as-department-group-add:
            path: /v1/admin/subject/group/department_group_add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-teacher-add:
            path: /v1/admin/teacher/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-teacher-add-to-faculty:
            path: /v1/admin/faculty/add_teacher
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-teacher-rank-add:
            path: /v1/admin/teacher/rank/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-university-add:
            path: /v1/admin/university/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-assignment-add:
            path: /v1/subject/assignment/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-assignment-content-get:
            path: /v1/subject/assignment/{s3_key}
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-assignment-mark-add:
            path: /v1/subject/assignment/mark/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-assignment-solution-add:
            path: /v1/subject/assignment/solution/add
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-assignment-solution-content-get:
            path: /v1/subject/assignment/solution/{s3_key}
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-student-assignments-get:
            path: /v1/subject/assignments/student
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-teacher-assignments-get:
            path: /v1/subject/assignments/teacher
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-student-diary-get:
            path: /v1/student/diary
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-subject-group-messages-get:
            path: /v1/chat/messages/{subject_group_name}
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-subject-group-message-send:
            path: /v1/chat/send_message
            task_processor: main-task-processor
            method: POST,OPTIONS

        handler-subject-groups-get:
            path: /v1/subject_groups
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-generate-presigned-url:
            path: /v1/presigned-url
            task_processor: main-task-processor
            method: GET,OPTIONS

        handler-grant-admin-rules:
            path: /v1/admin/grant
            task_processor: main-task-processor
            method: POST,OPTIONS

        #postgres-db-1:
        #    dbconnection: $dbconnection
        #    blocking_task_processor: fs-task-processor
        #    dns_resolver: async
        #    sync-start: false
        #    connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor
