name: Docker build

'on':
    schedule:
      - cron: '30 5 * * 1'  # Every Monday at 5:30
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                submodules: true

          - name: Reuse ccache directory
            uses: actions/cache@v2
            with:
                path: .ccache
                key: 'ccache-dir-${{github.ref}}_run-${{github.run_number}}'
                restore-keys: |
                    ccache-dir-${{github.ref}}_run-
                    ccache-

          - name: Build
            run: make docker-build-release

